// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otapyzpvhzvakigmvnvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90YXB5enB2aHp2YWtpZ212bnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjQ3MTYsImV4cCI6MjA2MjEwMDcxNn0.ZkEypUzuIuEsSz6by_aRwfKm8VhQ6e4JhjPvid9xmUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);